# Generated by Django 5.1.7 on 2025-03-11 22:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Car Make Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Car Make Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Brand Logo URL"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Official Website"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Founded Year"
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Make",
                "verbose_name_plural": "Car Makes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Car Model Name"),
                ),
                (
                    "type_car",
                    models.CharField(
                        choices=[
                            ("SEDAN", "Sedan"),
                            ("SUV", "SUV"),
                            ("WAGON", "WAGON"),
                        ],
                        default="SUV",
                        max_length=100,
                        verbose_name="Car Type",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=2025,
                        validators=[
                            django.core.validators.MinValueValidator(2015),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                        verbose_name="Car Year",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangoapp.carmake",
                        verbose_name="Car Make",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Model",
                "verbose_name_plural": "Car Models",
                "ordering": ["-year", "maker__name", "name"],
            },
        ),
    ]
